### PR TITLE
config: Update clearcontainers config for the latest kernel version

### PR DESCRIPTION
**Pull request by amshinde**
Signed-off-by: Archana Shinde <archana.m.shinde@intel.com>

### CODE REVIEW

**Comment by jodh-intel** [comment]
Please can add a description in the commit message to conform to the usual standard.

I suggest adding details of which kernel version this change is for.

**Comment by grahamwhaley** [comment]
@amshinde agree with @jodh-intel - I am a little confused if you are updating to a new kernel version at this time, or if this is just a config update/change for the current 'kernel version' (which in this tree is 4.9.10 afaict). I suspect the latter - I don't believe you are actually updating the kernel version, just the config setup for this kernel with new features we require ?

**Comment by jcvenegas** [comment]
@amshinde  Added a new branch https://github.com/clearcontainers/linux/tree/v4.9.27-clear-containers. I think we could change the default branch  ( or rebase master :( ?  )

**Comment by amshinde** [comment]
@jcvenegas Thanks! I'd vote for making the v.4.9.27 branch as default.

**Pull request closed without merging**
